version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sanitize-html
    versions:
    - 2.3.2
  - dependency-name: sequelize
    versions:
    - 6.5.1
  - dependency-name: socket.io
    versions:
    - 4.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: socket.io-client
    versions:
    - 4.0.0
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: html-entities
    versions:
    - 2.1.1
